from odoo import api, fields, models

class UsmoAssessment(models.Model):
    _name ='usmo.assessment'

    Answer01 = fields.Char(string='Answer 01')
    Answer02 = fields.Char(string='Answer 02')
    Answer03 = fields.Char(string='Answer 03')
    Answer04 = fields.Char(string='Answer 04')
    Answer05 = fields.Char(string='Answer 05')
    Answer06 = fields.Char(string='Answer 06')
    Answer07 = fields.Char(string='Answer 07')
    Answer08 = fields.Char(string='Answer 08')
    Answer09 = fields.Char(string='Answer 09')
    Answer10 = fields.Char(string='Answer 10')
    Answer11 = fields.Char(string='Answer 11')
    Answer12 = fields.Char(string='Answer 12')
    Answer13 = fields.Char(string='Answer 13')
    Answer14 = fields.Char(string='Answer 14')
    Answer15 = fields.Char(string='Answer 15')
    Answer16 = fields.Char(string='Answer 16')
    Answer17 = fields.Char(string='Answer 17')
    Answer18 = fields.Char(string='Answer 18')
    Answer19 = fields.Char(string='Answer 19')
    Answer20 = fields.Char(string='Answer 20')
    Answer21 = fields.Char(string='Answer 21')
    Answer22 = fields.Char(string='Answer 22')
    Answer23 = fields.Char(string='Answer 23')
    Answer24 = fields.Char(string='Answer 24')
    Answer25 = fields.Char(string='Answer 25')
    Answer26 = fields.Char(string='Answer 26')
    Answer27 = fields.Char(string='Answer 27')
    Answer28 = fields.Char(string='Answer 28')
    Answer29 = fields.Char(string='Answer 29')
    Answer30 = fields.Char(string='Answer 30')
    AssessedBy = fields.Char(string='Assessed By')
    AssessmentType = fields.Char(string='Assessment Type')
    Client = fields.Char(string='Client')
    CreatedDT = fields.Char(string='Created DT')
    RowGUID = fields.Char(string='Row GUID')
    Voucher = fields.Char(string='Voucher')
